apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workshop-infra
  namespace: openshift-gitops
spec:
  destination:
    namespace: ''
    server: https://kubernetes.default.svc
  source:
    path: resources
    repoURL: https://github.com/mostmark/workshopinstall.git
    targetRevision: HEAD
  sources: []
  project: default