apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- che-cluster.yaml
- gitea-instance.yaml
- devspaces-ns.yaml
- openshift-pipelines.yaml
- openshift-dev-spaces.yaml
patches:
- patch: |-
    - op: replace
      path: /spec/giteaUserNumber
      value: 1
  target:
    group: pfe.rhpds.com
    kind: Gitea
    name: gitea-workshop
    version: v1