apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workshop-infra
spec:
  generators:
    - list:
        elements:
          - name: gitea
            namespace: openshift-operators
            path: OLMDeploy
            repoURL: https://github.com/rhpds/gitea-operator
            targetRevision: HEAD
            syncWave: 0
          - name: operators-base
            namespace: openshift-operators
            repoURL: https://github.com/bmeklund/workshop-install
            path: operators-base
            targetRevision: HEAD
            syncWave: 1
          - name: operators-instances
            namespace: default
            repoURL: https://github.com/bmeklund/workshop-install
            path: operators-instances
            targetRevision: HEAD
            syncWave: 2
  template:
    metadata:
      labels:
        app: '{{name}}'
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{targetRevision}}'
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true # Only sync resources that are out of sync